# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "468ef4c11d8060bde9d8a9d017ef4142"
name = "Motor de Descuentos"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[webhooks]
api_version = "2026-04"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
