# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a4999b35af564fddb4c2a05ff9c630a"
name = "Motor de Descuentos"
application_url = "https://shopifyfuction.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[webhooks]
api_version = "2026-04"

[auth]
redirect_urls = [ "https://shopifyfuction.onrender.com/api/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
