api_version = "2026-04"
uid = "9914f07e-a566-2496-235a-116d014311a2491dccbb"

[[extensions]]
name = "Descuento por cruce de grupos de precio"
handle = "cross-group-discounts"
type = "product_discounts"
description = "Descuento por cruce de grupos de precio"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/"
details = "/"
